services:
  - type: web
    name: browseruse-relay
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python server.py"
    envVars:
      - key: BROWSERUSE_API_KEY
        sync: false
